# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.exporter.fledge}}
  name: {{.Values.edgex.app.exporter.fledge}}
spec:
  type: NodePort
  ports:
    - name: "http"
      port: {{.Values.edgex.port.exporter.fledge}}
      appProtocol: tcp
      nodePort: 30884
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.exporter.fledge}}
status:
  loadBalancer: {}
