# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: maleaf-dataset-volume
spec:
  storageClassName: "{{.Values.maleaf.storage.className}}"
  claimRef:
    name: maleaf-dataset
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/maleaf-dataset"
