reporting_identifier: cluster_0
prometheus_url: http://160.85.252.183:32090
lasm_server_urls:
  - "http://160.85.252.183:32102"
#  - "http://127.0.0.1:32102"
#  - "http://127.0.0.1:5002"
trails_server_urls:
#  - "http://127.0.0.1:32102"
  - "http://160.85.252.183:32102"
#  - "http://127.0.0.1:5002"

# General properties
step_interval: 60
number_of_training_data: 126
number_of_test_data: 32
number_of_test_false_positive_data: 30
number_of_initial_steps: 30
number_of_concurrent_faults: 1
use_archive: true
test_false_positive: true
output_folder: results_svm
training_data:
  - dataset/double_failures/training_data_20240109-174641.csv
test_data:
  - dataset/double_failures/training_data_20240110-064448.csv

services_for_fault_injection:
  - edgex-core-data
  - edgex-core-command
  - edgex-ui
  - edgex-core-metadata
  - edgex-device-mqtt
  - edgex-redis
  - edgex-mqtt-broker
  - edgex-exporter-fledge
services_skipped:
  - edgex-device-rest
  - edgex-core-consul
  - edgex-device-virtual
  - edgex-app-rules-engine
  - edgex-sys-mgmt-agen
  - edgex-kuiper
  - edgex-support-notifications
  - edgex-support-scheduler
metrics_skipped:
  #- cpu
  - error
  - nothing # just a placeholder
experiments_skipped:
  #cpu: 2
 nothing: 99 # just a placeholder

# Choose from 'svm', 'random_forest' or 'cbn'
rca_algorithm: 'svm'

# SVM properties
svm_kernel: 'linear'
random_state_svm: 42

# Random Forest properties
number_of_trees: 100
random_state_rf: 42

# CBN properties
min_number_of_edges_per_node: 5
weak_link_threshold: 0.05

# Log properties
log_level: "INFO"
time_format: '%H:%M:%S'
logging_format: "%(asctime)s.%(msecs)03d-> %(message)s"
