FROM python:3.10-slim

RUN apt-get update && apt-get install -y python3-pip python3-dev

ADD requirements-maleaf.txt .
RUN pip install -r requirements-maleaf.txt

ADD main.py .

ENTRYPOINT ["python3", "./main.py"]