FROM python:3.10-slim

RUN apt-get update && apt-get install -y python3-pip python3-dev pkg-config graphviz-dev graphviz

RUN pip install pygraphviz==1.10
RUN pip install torch==1.13.1 --extra-index-url https://download.pytorch.org/whl/cpu

ADD requirements-maleaf.txt .
RUN pip install -r requirements-maleaf.txt

RUN mkdir dataset
RUN mkdir cbn_graph
RUN mkdir random_forest_tree
RUN mkdir structure_models

ADD main.py .
ADD anomaly_detection.py .
ADD chaos_mesh_utils.py .
ADD config.py .
ADD data_manipulation.py .
ADD generate_model.py .
ADD lasm_utils.py .
ADD metric.py .
ADD rca.py .
ADD sla.py .
ADD test_data.py .
ADD models models

ENTRYPOINT ["python3", "./main.py"]
