# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.mqttbroker}}
  name: {{.Values.edgex.app.mqttbroker}}
spec:
  replicas: {{.Values.edgex.replicas.mqttbroker}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.mqttbroker}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.mqttbroker}}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {{.Values.edgex.app.mqttbroker}}
        image: {{.Values.edgex.image.mqttbroker.repository}}:{{.Values.edgex.image.mqttbroker.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{.Values.edgex.port.mqttbroker}}
        envFrom:
        - configMapRef:
              name: edgex-common-variables
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        startupProbe:
          tcpSocket:
            port: {{.Values.edgex.port.mqttbroker}}
          periodSeconds: 1
          failureThreshold: 120
        livenessProbe:
          tcpSocket:
            port: {{.Values.edgex.port.mqttbroker}}
        volumeMounts:
        - name: configmap
          mountPath: /mosquitto/config        
      {{- if .Values.edgex.resources.mqttbroker.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.mqttbroker.limits.memory }}
            cpu: {{ .Values.edgex.resources.mqttbroker.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.mqttbroker.requests.memory }}
            cpu: {{ .Values.edgex.resources.mqttbroker.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.mqttbroker}}
      restartPolicy: Always
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumes:
      - name: configmap
        configMap:
          name: edgex-mqtt-broker-configmap
          items:
          - key: mosquitto.conf
            path: mosquitto.conf
      {{- if .Values.edgex.security.enabled }}
      - name: edgex-init
        persistentVolumeClaim:
          claimName: edgex-init
      - name: edgex-secrets
        persistentVolumeClaim:
          claimName: edgex-secrets
      - name: run-tmp
        emptyDir:
          medium: Memory
          sizeLimit: 64Mi
      {{- end}}