# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.mqttbroker}}
  name: {{.Values.edgex.app.mqttbroker}}
spec:
  type: NodePort
  ports:
    - name: "http"
      port: {{.Values.edgex.port.mqttbroker}}
      appProtocol: tcp
      nodePort: 30883
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.mqttbroker}}
status:
  loadBalancer: {}
