reporting_identifier: cluster_1
prometheus_url: "http://prometheus.istio-system.svc.cluster.local:9090"
lasm_server_urls:
  - "http://lasm-server.maleaf.svc.cluster.local:5001"
#  - "http://127.0.0.1:32002"
#  - "http://127.0.0.1:5001"
trails_server_urls:
  - "http://lasm-server.maleaf.svc.cluster.local:5001"
#  - "http://127.0.0.1:32002"
#  - "http://127.0.0.1:5001"

step_interval: 60
number_of_training_data: 100
number_of_test_data: 41
number_of_test_false_positive_data: 24
number_of_initial_steps: 30
number_of_concurrent_faults: 1
use_archive: false
test_false_positive: true
output_folder: results
training_data:
#  - dataset_v6/training_data_20221101-194735.csv
test_data:
#  - dataset_v4/training_data_20221025-140923.csv




min_number_of_edges_per_node: 5
weak_link_threshold: 0.05
services_for_fault_injection:
  - edgex-core-data
  - edgex-core-command
  - edgex-ui
  - edgex-core-metadata
  - edgex-device-mqtt
  - edgex-redis
  - edgex-mqtt-broker
  - edgex-exporter-fledge
services_skipped:
  - edgex-device-rest
  - edgex-core-consul
  - edgex-device-virtual
  - edgex-app-rules-engine
  - edgex-sys-mgmt-agen
  - edgex-kuiper
  - edgex-support-notifications
  - edgex-support-scheduler
metrics_skipped:
  - cpu
  - error
experiments_skipped:
  cpu: 2

log_level: "INFO"
time_format: '%H:%M:%S'
logging_format: "%(asctime)s.%(msecs)03d-> %(message)s"

test_variable: "test variable"